import { onMount } from "solid-js"
import { useTheme } from "@opencode/ui/theme"
import harness from "./theme.json"
import type { DesktopTheme } from "@opencode/ui/theme"

/**
 * Register the product's palette and make it the active theme.
 *
 * WHY A NEW THEME RATHER THAN EDITING THEIRS. The obvious move is to overwrite
 * `oc-2.json`, which is the hardcoded default. Do not: that file carries a
 * ~205-entry `v2Overrides` block per mode, generated by a script that bakes
 * their static stylesheet into the JSON, and `v2Overrides` is merged LAST. A
 * palette written underneath it is masked in the whole v2 token layer, so
 * roughly half the interface stays OpenCode grey while the other half turns
 * warm - and nothing errors. It is the only silent failure the research turned
 * up, and every other theme they ship is free of it.
 *
 * Registering a theme sidesteps it by construction. `load()` in their
 * ThemeProvider checks `store.themes[id]` before reaching for the bundled
 * files, so a registered theme wins, and ours simply has no `v2Overrides` to
 * mask anything.
 *
 * WHAT THE PALETTE IS. Seven required colours and three optional ones, from
 * which their resolver generates nine hue ramps of twelve steps in OKLCH -
 * 453 custom properties per mode. `generateNeutralScale` sinks the neutral
 * seed to a background and then mixes toward `ink` across twelve tone stops,
 * which is why one warm-tinted seed produces warm greys, warm borders and warm
 * surfaces without any of them being stated.
 *
 * The values are this product's own, from its token file: the charcoal ground,
 * the bone ink, the cobalt that means "live", and the four claim colours -
 * fits, spills, wont, info - mapped onto their success/warning/error/info.
 */
export function ApplyHarnessTheme() {
  const theme = useTheme()

  onMount(() => {
    theme.registerTheme(harness as DesktopTheme)
    // Only if the person has not already chosen something else. Their
    // ThemeProvider restores a stored choice, and overriding that every launch
    // would make the theme picker look broken.
    if (theme.themeId() === "oc-2") theme.setTheme(harness.id)
  })

  return null
}
