"""The reskin's one silent failure, made loud.

OpenCode's default theme, `oc-2.json`, carries a `v2Overrides` block of about
205 entries per mode that pins every v2 colour primitive back to their own
values. It is generated by a script that bakes their static stylesheet into the
JSON, and it is merged LAST.

So a palette written into that file is simply masked across the whole v2 token
layer. Roughly half the interface keeps OpenCode's grey while the other half
turns warm, no error is raised, no build fails, and the only symptom is that it
looks subtly wrong in a way nobody can name. Every other theme they ship -
nord, dracula, cobalt2 - has no `v2Overrides`. oc-2 is the anomaly.

This product avoids it by construction rather than by remembering to delete
409 lines: it registers its own theme, and their `load()` prefers a registered
theme over a bundled file. The tests below hold that construction in place.

They read the theme JSON as data. They do not resolve colours or assert on
generated ramps - that is their resolver's business and would be a test of
OKLCH arithmetic, not of this decision.
"""

from __future__ import annotations

import json
import unittest
from pathlib import Path

import support  # noqa: F401  - puts the repo root on the path

REPO = Path(__file__).resolve().parent.parent
THEME = REPO / "web" / "src" / "brand" / "theme.json"
APPLY = REPO / "web" / "src" / "brand" / "apply-theme.tsx"

#: Their palette contract: seven required, and the optional ones this product
#: sets. Derived from `@opencode/ui/src/theme/types.ts`.
REQUIRED = ("neutral", "ink", "primary", "success", "warning", "error", "info")


class TheThemeIsWellFormedTest(unittest.TestCase):
    def setUp(self):
        self.theme = json.loads(THEME.read_text(encoding="utf-8"))

    def test_it_declares_both_modes(self):
        """A variant that is missing does not fall back to theirs - their
        resolver takes `isDark` and reads that key."""
        for mode in ("light", "dark"):
            with self.subTest(mode=mode):
                self.assertIn(mode, self.theme)

    def test_every_required_palette_colour_is_present_in_both_modes(self):
        """DERIVED FROM THE CONTRACT, not hand-listed per mode, so a colour
        added to REQUIRED is checked in both without editing two places."""
        for mode in ("light", "dark"):
            palette = self.theme[mode]["palette"]
            for name in REQUIRED:
                with self.subTest(mode=mode, colour=name):
                    self.assertIn(name, palette)
                    self.assertRegex(palette[name], r"^#[0-9a-fA-F]{6}$")

    def test_a_variant_declares_a_palette_and_not_seeds(self):
        """Their resolver throws if both are given, and `seeds` is the legacy
        shape with no `ink` - which is the input that makes the neutral ramp
        warm. `palette` also switches their `compact` path on."""
        for mode in ("light", "dark"):
            with self.subTest(mode=mode):
                self.assertIn("palette", self.theme[mode])
                self.assertNotIn("seeds", self.theme[mode])


class TheTrapIsAvoidedTest(unittest.TestCase):
    def setUp(self):
        self.theme = json.loads(THEME.read_text(encoding="utf-8"))

    def test_no_v2_overrides_anywhere(self):
        """THE WHOLE POINT OF THIS FILE. `v2Overrides` merges last and would
        mask the palette in silence."""
        for mode in ("light", "dark"):
            with self.subTest(mode=mode):
                self.assertNotIn(
                    "v2Overrides",
                    self.theme[mode],
                    "v2Overrides merges last and masks the palette across the "
                    "entire v2 token layer, with no error. Delete it.",
                )

    def test_the_id_is_not_theirs(self):
        """Registering under `oc-2` would collide with the bundled file that
        carries the overrides, and their loader special-cases that id."""
        self.assertNotEqual(self.theme["id"], "oc-2")

    def test_the_theme_is_registered_rather_than_written_over_theirs(self):
        """The construction, asserted where it lives: we call registerTheme,
        not edit node_modules."""
        source = APPLY.read_text(encoding="utf-8")
        self.assertIn("registerTheme", source)
        self.assertIn(self.theme["id"], source)

    def test_a_stored_choice_is_not_overridden_every_launch(self):
        """Their provider restores the person's theme. Forcing ours on top of
        that would make the theme picker look broken."""
        self.assertIn("oc-2", APPLY.read_text(encoding="utf-8"))


class TheColoursAreThisProductsTest(unittest.TestCase):
    """Not an aesthetic assertion - a provenance one. These four are quoted in
    the token file with measured contrast ratios behind them, and a reskin that
    quietly drifts off them is the thing this catches."""

    def setUp(self):
        self.dark = json.loads(THEME.read_text(encoding="utf-8"))["dark"]["palette"]

    def test_the_ground_is_the_warm_charcoal(self):
        self.assertEqual(self.dark["neutral"].upper(), "#1F1F1D")

    def test_the_ink_is_the_bone(self):
        self.assertEqual(self.dark["ink"].upper(), "#F8F3E6")

    def test_the_accent_is_the_cobalt(self):
        self.assertEqual(self.dark["primary"].upper(), "#6088EE")
        self.assertEqual(self.dark["interactive"].upper(), "#6088EE")

    def test_the_claim_colours_map_onto_their_status_colours(self):
        """fits / spills / wont are this product's vocabulary; success /
        warning / error are theirs. The mapping is the reskin."""
        self.assertEqual(self.dark["success"].upper(), "#5FD3A8")   # fits
        self.assertEqual(self.dark["warning"].upper(), "#E8B45E")   # spills
        self.assertEqual(self.dark["error"].upper(), "#EF7E7E")     # wont


if __name__ == "__main__":
    unittest.main()
