"""Run the clean-machine test in Windows Sandbox, or say exactly why it cannot.

## What this answers

`.github/workflows/gate.yml` draws the line this script is built to cross:
*"the clean-machine test is a person installing on a computer that has never
seen this repository and reaching a diagnosed problem without asking a
question. A runner is a fresh machine, which is most of it, and it is not a
person."* `docs/THE_PLAN.md` Phase C recorded it BLOCKED for wanting a second
computer.

**Windows Sandbox is a second computer.** It boots clean, has no Python, no
WebView2 runtime, no repository and no `%LOCALAPPDATA%` belonging to this
product, and it is destroyed on close. That covers the mechanical half of the
test - can somebody who has nothing get to a working engine without opening a
terminal - and `scripts/clean_machine.ps1` measures it.

**It is still not a person.** Whether what they see is UNDERSTANDABLE is not
something a script can measure, and this does not pretend to. What it produces
is a log, a `result.json` and the output of `mlh doctor` from inside, which is
the material a person needs to judge the other half.

## Why a generated .wsb and not a committed one

A `.wsb` carries absolute host paths. A committed one would carry the author's,
which is the kind of file that works on exactly one machine and looks like it
should work everywhere. This writes one for wherever the repository is.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BUNDLE = ROOT / "src-tauri" / "target" / "release" / "bundle"
RESULTS = ROOT / ".clean-machine"

#: Windows Sandbox always logs in as this account and always puts mapped
#: folders on its desktop. Not configurable, which is why it can be a constant.
SANDBOX_DESKTOP = r"C:\Users\WDAGUtilityAccount\Desktop"

WSB = """<Configuration>
  <!-- Generated by scripts/clean_machine_test.py. Absolute paths are this
       machine's, which is why this file is generated and not committed. -->
  <Networking>Enable</Networking>
  <MappedFolders>
    <MappedFolder>
      <HostFolder>{installer}</HostFolder>
      <SandboxFolder>{desktop}\installer</SandboxFolder>
      <!-- READ-ONLY. The sandbox is disposable and the host is not; nothing in
           here should be able to write into a build directory. -->
      <ReadOnly>true</ReadOnly>
    </MappedFolder>
    <MappedFolder>
      <HostFolder>{scripts}</HostFolder>
      <SandboxFolder>{desktop}\scripts</SandboxFolder>
      <ReadOnly>true</ReadOnly>
    </MappedFolder>
    <MappedFolder>
      <HostFolder>{results}</HostFolder>
      <SandboxFolder>{desktop}\\results</SandboxFolder>
      <!-- The one writable door, and it exists because a test whose findings
           die with the sandbox is a test nobody can read. -->
      <ReadOnly>false</ReadOnly>
    </MappedFolder>
  </MappedFolders>
  <LogonCommand>
    <Command>powershell.exe -ExecutionPolicy Bypass -NoProfile -File {desktop}\scripts\clean_machine.ps1</Command>
  </LogonCommand>
</Configuration>
"""


def sandbox_is_available() -> tuple[bool, str]:
    """Is Windows Sandbox installed AND past the reboot it asks for?"""
    exe = Path(os.environ.get("WINDIR", r"C:\Windows")) / "System32" / "WindowsSandbox.exe"
    if exe.is_file():
        return True, str(exe)
    return False, (
        "WindowsSandbox.exe is not on this machine yet. Enable the feature and "
        "REBOOT - the feature reports Enabled before the restart and the "
        "executable does not appear until after it:\n"
        "  Enable-WindowsOptionalFeature -Online "
        "-FeatureName Containers-DisposableClientVM -All"
    )


def installers() -> list[Path]:
    if not BUNDLE.is_dir():
        return []
    return sorted(
        [p for p in BUNDLE.rglob("*.exe")] + [p for p in BUNDLE.rglob("*.msi")]
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--write-only",
        action="store_true",
        help="Write the .wsb and print how to start it, rather than starting it.",
    )
    args = parser.parse_args(sys.argv[1:] if argv is None else argv)

    built = installers()
    if not built:
        raise SystemExit(
            f"no installer under {BUNDLE}. Build one first:\n"
            "  ./frontend/node_modules/.bin/tauri build"
        )
    for one in built:
        print(f"installer: {one.name} ({one.stat().st_size / 1048576:.1f} MB)")

    RESULTS.mkdir(parents=True, exist_ok=True)
    for stale in RESULTS.glob("*"):
        # A previous run's result.json sitting beside a failed run is how
        # somebody reads last week's answer as this one's.
        if stale.is_file():
            stale.unlink()

    config = RESULTS / "clean-machine.wsb"
    config.write_text(
        WSB.format(
            installer=BUNDLE,
            scripts=ROOT / "scripts",
            results=RESULTS,
            desktop=SANDBOX_DESKTOP,
        ),
        encoding="utf-8",
    )
    print(f"wrote {config}")

    available, detail = sandbox_is_available()
    if not available:
        print(f"\nNOT RUN. {detail}")
        print(f"\nAfter the reboot:\n  python scripts/clean_machine_test.py")
        return 1

    if args.write_only:
        print(f"\nStart it with:\n  {config}")
        return 0

    print("\nstarting Windows Sandbox; it will install and run without anything typed")
    subprocess.run([detail, str(config)], check=True)
    print(f"results will appear in {RESULTS}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
